FROM python:3.11-alpine

WORKDIR /app

COPY requirements.txt .
RUN apk add --no-cache gcc musl-dev libffi-dev python3-dev make \
    && pip install --upgrade pip \
    && pip install -r requirements.txt

COPY . .

CMD ["python", "app.py"]
